openapi: 3.0.0
info:
  title: Decision Maker API
  description: Decision Maker API
  version: 0.0.1
servers:
  - url: /api
paths:
  /ping:
    $ref: paths/ping.yml
  /user:
    $ref: ./paths/user.yml
  /user/{id}:
    $ref: ./paths/user_{id}.yml
  /device:
    $ref: paths/device.yml
  /device/{id}:
    $ref: paths/device_{id}.yml
  /workflow:
    $ref: paths/workflow.yml
  /workflow/{id}:
    $ref: paths/workflow_{id}.yml
  /workflow/{id}/devices:
    $ref: paths/workflow_{id}_devices.yml
